# Generated by Django 4.2 on 2023-04-09 14:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import secrets


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accesorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre", models.CharField(max_length=45)),
                ("Descripcion", models.TextField()),
                ("Imagen", models.ImageField(upload_to="Accesorio")),
                ("Icon", models.CharField(max_length=45, null=True)),
                ("Status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CategoriaCoche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre", models.CharField(max_length=45)),
                ("Descripcion", models.TextField()),
                ("Imagen", models.ImageField(upload_to="CategoriaCoche")),
                ("Icon", models.CharField(max_length=45, null=True)),
                ("Status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Coche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre", models.CharField(max_length=200)),
                ("Anio", models.CharField(max_length=45, null=True)),
                ("Modelo", models.CharField(max_length=45, null=True)),
                ("Descripcion", models.TextField()),
                ("Imagen", models.ImageField(upload_to="Coche")),
                ("NumeroPuertas", models.IntegerField(default=4)),
                ("Capacidad", models.IntegerField(default=5)),
                ("Kilometraje", models.DecimalField(decimal_places=5, max_digits=10)),
                ("Gasolina", models.DecimalField(decimal_places=5, max_digits=10)),
                ("Latitud", models.CharField(max_length=45, null=True)),
                ("Longitud", models.CharField(max_length=45, null=True)),
                ("Tarifa", models.DecimalField(decimal_places=5, max_digits=10)),
                ("PrecioRenta", models.DecimalField(decimal_places=5, max_digits=10)),
                ("Disponibilidad", models.BooleanField(default=True)),
                ("Icon", models.CharField(max_length=45, null=True)),
                ("Status", models.BooleanField(default=False)),
                (
                    "CategoriaCoche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.categoriacoche",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarcaCoche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre", models.CharField(max_length=45)),
                ("Descripcion", models.TextField()),
                ("Imagen", models.ImageField(upload_to="MarcaCoche")),
                ("Icon", models.CharField(max_length=45, null=True)),
                ("Status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TipoIncidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre", models.CharField(max_length=45)),
                ("Descripcion", models.TextField()),
                ("Imagen", models.ImageField(upload_to="TipoIncidencia")),
                ("Icon", models.CharField(max_length=45, null=True)),
                ("Status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TipoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre", models.CharField(max_length=45)),
                ("Descripcion", models.TextField()),
                ("Imagen", models.ImageField(upload_to="TipoPago")),
                ("Icon", models.CharField(max_length=45, null=True)),
                ("Usuario", models.TextField(null=True)),
                ("Clave", models.TextField(null=True)),
                ("Key", models.TextField(null=True)),
                ("OtroDato", models.TextField(null=True)),
                ("Status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Transmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre", models.CharField(max_length=45)),
                ("Descripcion", models.TextField()),
                ("Imagen", models.ImageField(upload_to="Transmision")),
                ("Icon", models.CharField(max_length=45, null=True)),
                ("Status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre", models.CharField(max_length=200)),
                ("Descripcion", models.TextField()),
                ("Apellido", models.CharField(max_length=105, null=True)),
                ("Correo", models.CharField(max_length=200, null=True)),
                ("Token", models.TextField(null=True)),
                ("Direccion", models.TextField(null=True)),
                ("Ciudad", models.CharField(max_length=200, null=True)),
                ("Pais", models.CharField(max_length=200, null=True)),
                ("Telefono", models.CharField(max_length=45, null=True)),
                ("Edad", models.IntegerField(null=True)),
                ("ImagenLicencia", models.ImageField(null=True, upload_to="Licencias")),
                ("Imagen", models.ImageField(null=True, upload_to="Usuario")),
                ("VigenciaLicencia", models.DateField(null=True)),
                ("Status", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Inicio", models.DateTimeField()),
                ("Fin", models.DateTimeField()),
                ("FechaReservacion", models.DateTimeField()),
                ("Precio", models.DecimalField(decimal_places=5, max_digits=10)),
                ("Comentario", models.TextField()),
                ("Kilometraje", models.DecimalField(decimal_places=5, max_digits=10)),
                ("LatitudInicio", models.CharField(max_length=45, null=True)),
                ("LongitudInicio", models.CharField(max_length=45, null=True)),
                ("LatitudFin", models.CharField(max_length=45, null=True)),
                ("LongitudFin", models.CharField(max_length=45, null=True)),
                ("Status", models.BooleanField(default=True)),
                (
                    "Coche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.coche"
                    ),
                ),
                (
                    "Usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Fecha", models.DateTimeField()),
                ("Monto", models.DecimalField(decimal_places=5, max_digits=10)),
                ("Tarifa", models.DecimalField(decimal_places=5, max_digits=10)),
                ("Impuestos", models.DecimalField(decimal_places=5, max_digits=10)),
                ("Total", models.DecimalField(decimal_places=5, max_digits=10)),
                ("IdSeguimiento", models.TextField()),
                (
                    "Reservacion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.reservacion",
                    ),
                ),
                (
                    "TipoPago",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tipopago",
                    ),
                ),
                (
                    "Usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Incidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Fecha", models.DateTimeField()),
                ("Descripcion", models.TextField()),
                ("Otros", models.TextField()),
                ("Evidencia", models.ImageField(upload_to="EvidenciasIncidencia")),
                ("Status", models.BooleanField(default=False)),
                ("Revisada", models.BooleanField(default=False)),
                (
                    "Reservacion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.reservacion",
                    ),
                ),
                (
                    "TipoIncidencia",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tipoincidencia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="Fotos")),
                ("image_title", models.CharField(blank=True, max_length=120)),
                ("uploded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Coche",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coche_images",
                        to="core.coche",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploded_at"],
            },
        ),
        migrations.CreateModel(
            name="HistorialMantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Fecha", models.DateTimeField()),
                ("Ubicacion", models.TextField()),
                ("kilometraje", models.DecimalField(decimal_places=5, max_digits=10)),
                ("Latitud", models.DecimalField(decimal_places=5, max_digits=10)),
                ("Longitud", models.DecimalField(decimal_places=5, max_digits=10)),
                ("Averia", models.TextField()),
                ("Reparacion", models.TextField()),
                ("Detalles", models.TextField()),
                ("Status", models.BooleanField(default=False)),
                (
                    "Coche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.coche"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventosSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Fecha", models.DateTimeField()),
                ("Ubicacion", models.TextField(null=True)),
                ("kilometraje", models.DecimalField(decimal_places=5, max_digits=10)),
                ("Latitud", models.CharField(max_length=45, null=True)),
                ("Longitud", models.CharField(max_length=45, null=True)),
                ("Motor", models.BooleanField(default=False)),
                ("Sonido", models.BooleanField(default=False)),
                ("Luces", models.BooleanField(default=False)),
                ("Personas", models.IntegerField()),
                ("Status", models.BooleanField(default=False)),
                (
                    "Reservacion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.reservacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comentarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Fecha", models.DateTimeField()),
                ("Comentario", models.TextField()),
                ("Valoracion", models.IntegerField()),
                ("Evidencia", models.ImageField(upload_to="")),
                ("Icon", models.CharField(max_length=45, null=True)),
                ("Status", models.BooleanField(default=False)),
                (
                    "Coche",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coche_comentarios",
                        to="core.coche",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="coche",
            name="MarcaCoche",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.marcacoche"
            ),
        ),
        migrations.AddField(
            model_name="coche",
            name="Transmision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.transmision"
            ),
        ),
        migrations.CreateModel(
            name="ClavesAcceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Token",
                    models.CharField(
                        default=secrets.token_hex, editable=False, max_length=6
                    ),
                ),
                ("Status", models.BooleanField(default=False)),
                ("Fecha", models.DateTimeField()),
                (
                    "FechaVencimiento",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 9, 16, 27, 24, 964394, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "Coche",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.coche",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccesoriosCoche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Status", models.BooleanField(default=True)),
                (
                    "Accesorio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.accesorio",
                    ),
                ),
                (
                    "Coche",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.coche",
                    ),
                ),
            ],
        ),
    ]
