# Generated by Django 4.1 on 2023-04-09 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_clavesacceso_fechavencimiento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="user",
            new_name="UsuarioFK",
        ),
    ]
