# Generated by Django 4.1 on 2023-04-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_user_usuario_usuariofk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="Descripcion",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="Nombre",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
