# Generated by Django 4.1 on 2023-04-09 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_usuario_descripcion_alter_usuario_nombre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="UsuarioFK",
            new_name="userprofile",
        ),
    ]
