# Generated by Django 4.1 on 2023-04-11 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_coche_latitud_alter_coche_longitud_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pago",
            name="Reservacion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservacion_pagos",
                to="core.reservacion",
            ),
        ),
    ]
