# Generated by Django 4.1 on 2023-04-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_pago_reservacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coche",
            name="Latitud",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="coche",
            name="Longitud",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
