# Generated by Django 4.1 on 2023-04-12 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0010_alter_accesorioscoche_coche"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recompensa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre", models.CharField(max_length=45)),
                ("Descripcion", models.TextField()),
                ("Imagen", models.ImageField(upload_to="Recompensas")),
                ("Icon", models.CharField(max_length=45, null=True)),
                ("PuntosRequeridos", models.IntegerField()),
                ("Status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Reto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre", models.CharField(max_length=45)),
                ("Descripcion", models.TextField()),
                ("Imagen", models.ImageField(upload_to="Accesorio")),
                ("Icon", models.CharField(max_length=45, null=True)),
                ("Puntos", models.IntegerField()),
                ("Status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RetoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Status", models.BooleanField(default=True)),
                ("Fecha", models.DateTimeField()),
                (
                    "Reto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retos_usuario",
                        to="core.reto",
                    ),
                ),
                (
                    "Usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecompensasUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Fecha", models.DateTimeField()),
                ("FechaVencimiento", models.DateTimeField()),
                ("Status", models.BooleanField(default=True)),
                (
                    "Recompensa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recompensa_usuario",
                        to="core.recompensa",
                    ),
                ),
                (
                    "Usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
