# Generated by Django 4.1 on 2023-04-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_recompensa_reto_retousuario_recompensasusuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="PuntosUsuario",
            field=models.IntegerField(null=True),
        ),
    ]
