# Generated by Django 4.1 on 2023-04-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_usuario_puntosusuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="TotalKilometros",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="TotalViajes",
            field=models.IntegerField(null=True),
        ),
    ]
